server:
  port: 8080

spring:
  application:
    name: finderai
  datasource:
    url: jdbc:postgresql://localhost:5432/finderai_db
    username: postgres
    password:
  liquibase:
    enabled: true # true enable liquibase database setup/update
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true # true will show the sql in the log
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: UTC

logging:
  level:
    root: DEBUG

aiprovider:
  max-dimension: 1536 #set to match vector database column
  default-provider: huggingface
  provider:
    openai:
      api:
        base-url: https://api.openai.com/v1
        api-key: your_openai_api_key
        secret: 
        model: text-embedding-ada-002
    deepseek:
      api:
        base-url: https://api.deepseek.com/v1
        api-key: your_deepseek_api_key
        secret: 
        model: deepseek-embedding
    huggingface:
      api:
        base-url: https://api-inference.huggingface.co/pipeline/feature-extraction/
        api-key: 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
        secret: 
        model: sentence-transformers/all-MiniLM-L6-v2
